# Generated by Django 3.2.8 on 2021-11-21 10:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('oauth', '0002_auto_20211121_1518'),
    ]

    operations = [
        migrations.CreateModel(
            name='AirCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.ImageField(upload_to='')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Авиакомпания',
                'verbose_name_plural': 'Авиакомпании',
            },
        ),
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('IATA_code', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'Аэропорт',
                'verbose_name_plural': 'Аэропорты',
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Страна',
                'verbose_name_plural': 'Страны',
            },
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('Flight_ID', models.CharField(max_length=6, primary_key=True, serialize=False, verbose_name='Номер рейса')),
                ('DateFrom', models.DateTimeField(verbose_name='Время вылета')),
                ('DateTo', models.DateTimeField(verbose_name='Время прилета (прибл.)')),
                ('Miles', models.FloatField(default=0, verbose_name='Количетсво миль')),
                ('Company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company', to='tickets.aircompany', verbose_name='Компания')),
                ('airFrom', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='airFrom', to='tickets.airport', verbose_name='Вылет из')),
                ('airTo', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='airTo', to='tickets.airport', verbose_name='Прилет в')),
            ],
            options={
                'verbose_name': 'Рейс',
                'verbose_name_plural': 'Рейсы',
            },
        ),
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('document', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('birthDate', models.DateField(verbose_name='День рождения')),
                ('FIO', models.CharField(max_length=100)),
                ('citizenship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citizens', to='tickets.country')),
            ],
        ),
        migrations.CreateModel(
            name='Town',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='country', to='tickets.country')),
            ],
            options={
                'verbose_name': 'Город',
                'verbose_name_plural': 'Города',
            },
        ),
        migrations.AddField(
            model_name='airport',
            name='town',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets.town'),
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('Seq', models.IntegerField(default=1, primary_key=True, serialize=False, verbose_name='Номер')),
                ('Cost', models.IntegerField(verbose_name='Цена')),
                ('Seat', models.CharField(max_length=5, verbose_name='Место')),
                ('Customer', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='oauth.authuser', verbose_name='Покупатель')),
                ('FlightOfTicket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='tickets.flight')),
                ('Passenger', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='tickets.passenger', verbose_name='Пассажир')),
            ],
            options={
                'verbose_name': 'Билет',
                'verbose_name_plural': 'Билеты',
                'unique_together': {('Seq', 'FlightOfTicket')},
            },
        ),
    ]
