# Generated by Django 3.2.8 on 2021-12-02 20:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('oauth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AirCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.ImageField(upload_to='')),
                ('name', models.CharField(max_length=50)),
                ('discount_for_INF', models.IntegerField(default=90, verbose_name='Скидка для детей младше 2 лет')),
                ('discount_for_CHD', models.IntegerField(default=50, verbose_name='Скидка для детей от 2 до 14 лет')),
            ],
            options={
                'verbose_name': 'Авиакомпания',
                'verbose_name_plural': 'Авиакомпании',
            },
        ),
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('IATA_code', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'Аэропорт',
                'verbose_name_plural': 'Аэропорты',
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Страна',
                'verbose_name_plural': 'Страны',
            },
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('flight_ID', models.CharField(max_length=6, primary_key=True, serialize=False, verbose_name='Номер рейса')),
                ('dateFrom', models.DateTimeField(verbose_name='Время вылета')),
                ('dateTo', models.DateTimeField(verbose_name='Время прилета (прибл.)')),
                ('miles', models.FloatField(default=0, verbose_name='Количетсво миль')),
                ('airFrom', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='airFrom', to='tickets.airport', verbose_name='Вылет из')),
                ('airTo', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='airTo', to='tickets.airport', verbose_name='Прилет в')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company', to='tickets.aircompany', verbose_name='Компания')),
            ],
            options={
                'verbose_name': 'Рейс',
                'verbose_name_plural': 'Рейсы',
            },
        ),
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('document', models.CharField(max_length=25, primary_key=True, serialize=False, verbose_name='Документ')),
                ('birthDate', models.DateField(verbose_name='День рождения')),
                ('FIO', models.CharField(max_length=100, verbose_name='ФИО')),
                ('citizenship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citizens', to='tickets.country', verbose_name='Гражданство')),
            ],
            options={
                'verbose_name': 'Пассажир',
                'verbose_name_plural': 'Пассажиры',
            },
        ),
        migrations.CreateModel(
            name='Town',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='country', to='tickets.country')),
            ],
            options={
                'verbose_name': 'Город',
                'verbose_name_plural': 'Города',
            },
        ),
        migrations.AddField(
            model_name='airport',
            name='town',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets.town'),
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.IntegerField(verbose_name='Цена')),
                ('seat', models.CharField(max_length=5, verbose_name='Место')),
                ('is_bought', models.BooleanField(default=False, verbose_name='Куплен?')),
                ('customer', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='oauth.authuser', verbose_name='Покупатель')),
                ('escort_passenger', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='escort', to='tickets.passenger', verbose_name='Пассажир')),
                ('flightOfTicket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='tickets.flight')),
                ('passenger', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seat', to='tickets.passenger', verbose_name='Пассажир')),
            ],
            options={
                'verbose_name': 'Билет',
                'verbose_name_plural': 'Билеты',
                'unique_together': {('seat', 'flightOfTicket')},
            },
        ),
    ]
