# Generated by Django 3.2.8 on 2021-12-03 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('oauth', '0001_initial'),
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='customer',
        ),
        migrations.CreateModel(
            name='ReturnTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payments_data', models.CharField(max_length=30, verbose_name='Реквизиты')),
                ('cost', models.IntegerField()),
                ('return_date', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ReturnedTickets', to='oauth.authuser', verbose_name='Покупатель')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ReturnTicket', to='tickets.ticket', verbose_name='Билет')),
            ],
        ),
        migrations.CreateModel(
            name='BuyTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payments_data', models.CharField(max_length=30, verbose_name='Реквизиты')),
                ('payment_date', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='oauth.authuser', verbose_name='Покупатель')),
                ('ticket', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='BuysTicket', to='tickets.ticket', verbose_name='Билет')),
            ],
        ),
    ]
