# Generated by Django 3.2.8 on 2021-11-26 08:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('oauth', '0005_authuser_accept_code'),
        ('tickets', '0002_alter_passenger_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='Customer',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='oauth.authuser', verbose_name='Покупатель'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='Passenger',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='tickets.passenger', verbose_name='Пассажир'),
        ),
    ]
