# Generated by Django 3.2.8 on 2021-11-29 23:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_auto_20211126_1330'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='Is_bought',
            field=models.BooleanField(default=False, verbose_name='Куплен?'),
        ),
        migrations.AlterField(
            model_name='passenger',
            name='FIO',
            field=models.CharField(max_length=100, verbose_name='ФИО'),
        ),
        migrations.AlterField(
            model_name='passenger',
            name='citizenship',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citizens', to='tickets.country', verbose_name='Гражданство'),
        ),
        migrations.AlterField(
            model_name='passenger',
            name='document',
            field=models.CharField(max_length=25, primary_key=True, serialize=False, verbose_name='Документ'),
        ),
        migrations.AlterUniqueTogether(
            name='ticket',
            unique_together={('Seat', 'FlightOfTicket')},
        ),
    ]
