# Generated by Django 3.2.8 on 2021-11-30 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0004_auto_20211130_0412'),
    ]

    operations = [
        migrations.AddField(
            model_name='aircompany',
            name='discount_for_CHD',
            field=models.IntegerField(default=50, verbose_name='Скидка для детей от 2 до 14 лет'),
        ),
        migrations.AddField(
            model_name='aircompany',
            name='discount_for_INF',
            field=models.IntegerField(default=90, verbose_name='Скидка для детей младше 2 лет'),
        ),
    ]
